### ISSUE TITLE
Shared Locking?

### ISSUE THREAD

**Issue by theory** [theckman/go-flock#13]
Would it be possible to add support for shared locks (`LOCK_SH`) in addition to exclusive locks (`LOCK_EX`)? Seems like a natural extension, though I'm not sure what the proper API for it would be.

**Comment by theckman** [comment]
I don't see a reason why the support couldn't be extended to allow advisory (shared) locks. My initial implementation was built to implement the `sync.Locker` interface. So maybe we could continue taking inspiration from `synx.RWMutex` type and go with `RLock()`, `RTryLock()`, and `RUnlock()`?

One caveat is that we would also need to implement Windows support.

What do you think? Would you want to try and implement it?

**Comment by theory** [comment]
I could, yes, though I don't think I'd be able to test the Windows implementation. I don't see a Windows Travis CI instance, either.

**Comment by theckman** [comment]
I'm working on getting CI up for Windows. It's a bit of slog as I don't personally have a Windows box handy. I hope I can finish it this afternoon.

**Comment by theory** [comment]
Would we need a separate object? Otherwise Locked() is ambiguous.
